site_name: Repath Studio
site_description: Vector Graphics Editor
site_author: Konstantinos Kaloutas
site_url: https://repath.studio/
copyright: 2025 Â© Repath Studio

repo_url: https://github.com/repath-project/repath-studio
repo_name: repath-studio

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  custom_dir: theme
  favicon: assets/images/favicon.png
  features:
  - navigation.tabs
  - navigation.expand
  - navigation.indexes
  - announce.dismiss
  - navigation.instant
  - navigation.footer
  - content.code.copy
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/logo.svg
  palette:
    primary: pink-700
    accent: pink
  font: false

nav:
  - Home: index.md
  - Get Started:
    - get-started/download.md
    - get-started/shortcuts.md
    - Interactive Shell: get-started/interactive-shell.md
  - Contribute:
    - Develop: contribute/contributing.md
    - Code of Conduct: contribute/CODE_OF_CONDUCT.md
    - CLA: contribute/CLA.md
  - Roadmap:
    - Milestones: roadmap/milestones.md
    - roadmap/changelog.md
  - Blog:
    - blog/index.md
  - Policies:
    - Privacy: policies/privacy.md
    - Security: policies/security.md
    - License: policies/license.md

extra:
  generator: false
  social:
  - icon: fontawesome/solid/at
    link: mailto:contact@repath.studio
    name: Email us
  - icon: custom/matrix 
    link: https://matrix.to/#/#repath.studio:matrix.org
  - icon: fontawesome/brands/discord
    link: https://discord.gg/yzjY6W6ame
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/repath.studio/
  - icon: fontawesome/brands/github
    link: https://github.com/repath-project/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - search
  - glightbox
  - blog
  - git-revision-date-localized:
      exclude:
        - get-started/*
        - blog/*
        - contribute/*
        - roadmap/*
        - index.md
  - social:
      cards_layout_options:
        font_family: Sora
        background_color: red
